### PR TITLE
Build libfins with cmake

### PR DESCRIPTION
**Pull request by petrov-adg**
Allow to build shared library via CMAKE.

### CODE REVIEW

**Comment by lammertb** [comment]
Does this Cmake file work with Visual Studio?

**Comment by petrov-adg** [comment]
We doesn't use Visual Studio. It used in our OpenWRT project. See https://github.com/petrov-adg/qt5-openwrt/blob/master/libs/fins/Makefile

**Comment by petrov-adg** [comment]
Because of library Version etc, It's only draft. Maybe it make sense to change library version and add another cmake rules (static/shared/examples etc.).

```
/usr/src/openwrt/TMP(openwrt-19.07) » git clone https://github.com/lammertb/libfins.git
Klone nach 'libfins' ...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 1088 (delta 3), reused 6 (delta 1), pack-reused 1075
Empfange Objekte: 100% (1088/1088), 251.53 KiB | 524.00 KiB/s, Fertig.
Löse Unterschiede auf: 100% (921/921), Fertig.
----------------------------------------------------------------------------------------------------------------------
/usr/src/openwrt/TMP(openwrt-19.07*) » cd libfins
----------------------------------------------------------------------------------------------------------------------
/usr/src/openwrt/TMP/libfins(master) » nano CMakeLists.txt
----------------------------------------------------------------------------------------------------------------------
/usr/src/openwrt/TMP/libfins(master*) » cd ..
----------------------------------------------------------------------------------------------------------------------
/usr/src/openwrt/TMP(openwrt-19.07*) » mkdir BUILD_LIBFINS
----------------------------------------------------------------------------------------------------------------------
/usr/src/openwrt/TMP(openwrt-19.07*) » cd BUILD_LIBFINS
----------------------------------------------------------------------------------------------------------------------
/usr/src/openwrt/TMP/BUILD_LIBFINS(openwrt-19.07*) » cmake ../libfins
-- The C compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/src/openwrt/TMP/BUILD_LIBFINS
----------------------------------------------------------------------------------------------------------------------
/usr/src/openwrt/TMP/BUILD_LIBFINS(openwrt-19.07*) » make
Scanning dependencies of target fins-static
[  0%] Building C object CMakeFiles/fins-static.dir/src/fins_01_01_bcd16.c.o
[  1%] Building C object CMakeFiles/fins-static.dir/src/fins_01_01_bcd32.c.o
...
[ 99%] Building C object CMakeFiles/fins.dir/src/fins_utils.c.o
[100%] Linking C shared library libfins.so
[100%] Built target fins
----------------------------------------------------------------------------------------------------------------------
/usr/src/openwrt/TMP/BUILD_LIBFINS(openwrt-19.07*) » ls -lah
insgesamt 424K
drwxr-xr-x 3 user01 user01  220 Feb 18 12:28 .
drwxr-xr-x 4 user01 user01   80 Feb 18 12:27 ..
-rw-r--r-- 1 user01 user01  15K Feb 18 12:28 CMakeCache.txt
drwxr-xr-x 6 user01 user01  300 Feb 18 12:28 CMakeFiles
-rw-r--r-- 1 user01 user01 3.7K Feb 18 12:28 cmake_install.cmake
-rw-r--r-- 1 user01 user01 208K Feb 18 12:28 libfins.a
-rw-r--r-- 1 user01 user01 2.0K Feb 18 12:28 LibFinsConfig.cmake
lrwxrwxrwx 1 user01 user01   12 Feb 18 12:28 libfins.so -> libfins.so.1
lrwxrwxrwx 1 user01 user01   16 Feb 18 12:28 libfins.so.1 -> libfins.so.1.0.0
-rwxr-xr-x 1 user01 user01 112K Feb 18 12:28 libfins.so.1.0.0
-rw-r--r-- 1 user01 user01  78K Feb 18 12:28 Makefile
```

**Comment by lammertb** [comment]
I understand your specific use case, but I do not see how the general public will benefit from a build system that supports fewer target environments than the current.

**Pull request closed without merging**
